/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // ── Material Design color roles ─────────────────────────────────
        'on-surface': '#191c1e',
        'secondary-container': '#6cf8bb',
        'primary': '#006c49',
        'on-background': '#191c1e',
        'inverse-on-surface': '#eff1f3',
        'primary-container': '#6cf8bb',
        'secondary': '#006c49',
        'on-tertiary-fixed-variant': '#3f465c',
        'inverse-surface': '#2d3133',
        'secondary-fixed': '#6ffbbe',
        'outline-variant': '#c1c9bf',
        'on-tertiary-container': '#fefcff',
        'on-error': '#ffffff',
        'surface-tint': '#006c49',
        'tertiary-container': '#6c748b',
        'error-container': '#ffdad6',
        'surface-container-high': '#e6e8ea',
        'on-primary-fixed': '#002113',
        'error': '#ba1a1a',
        'surface-variant': '#e0e3e5',
        'surface-dim': '#d8dadc',
        'on-primary-fixed-variant': '#005236',
        'inverse-primary': '#4edea3',
        'on-error-container': '#93000a',
        'tertiary-fixed-dim': '#bec6e0',
        'primary-fixed': '#6ffbbe',
        'secondary-fixed-dim': '#4edea3',
        'surface': '#f7f9fb',
        'primary-fixed-dim': '#4edea3',
        'surface-container-low': '#f2f4f6',
        'outline': '#727971',
        'on-tertiary': '#ffffff',
        'on-secondary-container': '#00714d',
        'surface-container-highest': '#e0e3e5',
        'surface-bright': '#f7f9fb',
        'surface-container-lowest': '#ffffff',
        'tertiary-fixed': '#dae2fd',
        'surface-container': '#eceef0',
        'on-secondary-fixed-variant': '#005236',
        'on-tertiary-fixed': '#131b2e',
        'on-primary-container': '#00714d',
        'on-secondary-fixed': '#002113',
        'on-secondary': '#ffffff',
        'background': '#f7f9fb',
        'tertiary': '#545c72',
        'on-primary': '#ffffff',
        'on-surface-variant': '#5b403e',
      },
      // ── Border radius ────────────────────────────────────────────────
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      // ── Named spacing tokens ─────────────────────────────────────────
      spacing: {
        xs: '4px',
        base: '8px',
        sm: '12px',
        md: '24px',
        lg: '48px',
        xl: '80px',
        gutter: '24px',
        'margin-desktop': '48px',
        'margin-mobile': '16px',
      },
      // ── Typography ───────────────────────────────────────────────────
      fontFamily: {
        // Base stack — Aileron leads for all UI text
        sans: ['Aileron', 'system-ui', 'sans-serif'],
        // Display / headline roles
        'headline-xl':       ['Aileron', 'sans-serif'],
        'headline-lg':       ['Aileron', 'sans-serif'],
        'headline-lg-mobile':['Aileron', 'sans-serif'],
        'headline-md':       ['Aileron', 'sans-serif'],
        // Body + label roles
        'body-lg':  ['Aileron', 'system-ui', 'sans-serif'],
        'body-md':  ['Aileron', 'system-ui', 'sans-serif'],
        'body-sm':  ['Aileron', 'system-ui', 'sans-serif'],
        'label-md': ['Aileron', 'system-ui', 'sans-serif'],
        'label-sm': ['Aileron', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
